### ISSUE TITLE
Are we sure it can handle multiple packets

### ISSUE THREAD

**Issue by SodaqMoja** [kukua/concava-connector-spul#3]
From earlier discussion I read:

> In v0.6 the socket got closed after the buffer was processed. It's now immediately closing the socket and then processing the data, which hopefully fixes this problem.

That seems to suggest that it closes the socket after receiving the first packet. But it was my understanding that we can send one or more packets in the same session.

Just so we are clear about it: the SPUL connector should not close the socket by itself. It must wait for a close (or timeout) from the client.

**Comment by mauvm** [comment]
I was referring to the binary buffer that the SPUL connector receives, which contains the header and all the blocks. Sorry for the confusion. I usually call the binary data the 'buffer' and the sensor data itself the 'payload' (also for ConCaVa).

Nevertheless, when the SPUL connector has received all the binary data (device ID, number of blocks, block size, and blocks/payloads - https://github.com/kukua/concava-connector-spul/blob/881baa7518a8a3c8b78c95c76a1bf1d0c4de8367/src/connector.js#L53) the TCP socket can be closed, because the client is not waiting for a response. However I didn't take into account that the client closes the connection. So I will remove closing the socket.

**Comment by SodaqMoja** [comment]
I am still not sure that we talk about the same thing. The document describing the SPUL protocol is not clear on this.

The binary buffer that the SPUL connector receives is the "TCP frame" in the SPUL document. It talks about data packets. It does not say explicitely that you can transmit more than one data packet in a TCP session.

But the current implementation of WDT is relying on that. This can happen when communication failed for a while, it will send as many data packets as possible within one TCP session.

In other words, the SPUL connector server must wait until the connection is closed from the client side. And it should process all incoming data packets. Each packet is a SPUL data packet with header and the "blocks". Since each SPUL data packet has its own header it is possible that data from multiple devices is transmitted within one TCP session.

When you say: 

> when the SPUL connector has received all the binary data (device ID, number of blocks, block size, and blocks/payloads the TCP socket can be closed, because the client is not waiting for a response

That statement is not true.

**Comment by mauvm** [comment]
Good point and indeed the spec is not clear on this.

In the link above you can see the socket has a 'data' event in which it receives individual TCP frames. So since I've removed closing the socket it is able to receive multiple frames, which are individually processed (parsing the header and sending the blocks to ConCaVa).

**Comment by SodaqMoja** [comment]
Yes, I think so too, removing the close is the right solution
